require 'technoweenie/attachment_fu/backends/cloud_file_backend'
require 'technoweenie/attachment_fu/backends/db_file_backend'
require 'technoweenie/attachment_fu/backends/file_system_backend'
require 'technoweenie/attachment_fu/backends/s3_backend'
require 'technoweenie/attachment_fu/backends/s3v1_backend'
require 'technoweenie/attachment_fu/backends/s3v2_backend'
